### ISSUE TITLE
Select color on click and collapse the picker by default

### ISSUE THREAD

**Issue by zaalbarxx** [talamaska/angular-radial-color-picker#7]
Hi!
There are two things I'd like to be able to do: 
--select color when just clicking on the palette
--show only the color button without picker on initial render
Do you think you could find some time to work on this ? If not, could you guide me how to achieve this ? Because this whole hide/show logic is a bit unclear for me, it is based on some CSS classes and if you could tell me something more about it I could add such option and create PR. As for the selecting color on click I tried to add the event handler for `click` on `.color-palette` element, but it did not work, I assume it's because it sits under the `.rotator` element, so maybe you know some easy way to achieve this, if not then I'll dig into the code and try to play a bit with this. There is also one issue with the Propeller package, your package assumes that the Propeller is bound to `window` object so it does not play nicely with the modules. Would you like to go for some module bundler like Rollup ? It would also allow to write ES6 code which would be nice.
Looking forward for your suggestions

**Comment by talamaska** [comment]
@zaalbarxx Hi, I appreciate your feedback. Unfortunately this color picker has a specific behavior that was required from the initial moment. The whole experience of dragging a handle around the color gradient and choosing the color from the center knob - the current selected color indicator is required.
Here is the example we followed when we were building this component:
[https://www.uplabs.com/posts/material-colorpicker](https://www.uplabs.com/posts/material-colorpicker)
1. what you describe changes the whole logic of the color picker - so probably it won't be implemented. The current behavior is based on the angle of the rotation to calculate what color was chosen. What you describe can be done if the color gradient was loaded in canvas and when clicking on it, you could get the current pixel coordinates color value. Can be achieved but requires more math, plus the cursor x and y coordinates require some normalization.
2. If we show only the central color knob, how we are going to trigger the appearance of the color gradient?
Yes you are correct - all animations and appearances are based on css classes for lighter footprint and smoother animations.
CSS was not meant to be customized. 
The plugin is made to work on es5 with ionic v1 and angular 1.5. You are free to use any additional bundler for your needs. 
We will think about ES6 build, but most probably it will be in separate branch or something.
